export default [
    {
        "code": "GEN",
        "name": "Genesis",
        "numberOfChapters": 50,
        "order": 0,
    },
    {
        "code": "EXO",
        "name": "Exodus",
        "numberOfChapters": 40,
        "order": 1,
    },
    {
        "code": "LEV",
        "name": "Leviticus",
        "numberOfChapters": 27,
        "order": 2,
    },
    {
        "code": "NUM",
        "name": "Numbers",
        "numberOfChapters": 36,
        "order": 3,
    },
    {
        "code": "DEU",
        "name": "Deuteronomy",
        "numberOfChapters": 34,
        "order": 4,
    },
    {
        "code": "JOS",
        "name": "Joshua",
        "numberOfChapters": 24,
        "order": 5,
    },
    {
        "code": "JDG",
        "name": "Judges",
        "numberOfChapters": 21,
        "order": 6,
    },
    {
        "code": "RUT",
        "name": "Ruth",
        "numberOfChapters": 4,
        "order": 7,
    },
    {
        "code": "1SA",
        "name": "1 Samuel",
        "numberOfChapters": 31,
        "order": 8,
    },
    {
        "code": "2SA",
        "name": "2 Samuel",
        "numberOfChapters": 24,
        "order": 9,
    },
    {
        "code": "1KI",
        "name": "1 Kings",
        "numberOfChapters": 22,
        "order": 10,
    },
    {
        "code": "2KI",
        "name": "2 Kings",
        "numberOfChapters": 25,
        "order": 11,
    },
    {
        "code": "1CH",
        "name": "1 Chronicles",
        "numberOfChapters": 29,
        "order": 12,
    },
    {
        "code": "2CH",
        "name": "2 Chronicles",
        "numberOfChapters": 36,
        "order": 13,
    },
    {
        "code": "EZR",
        "name": "Ezra",
        "numberOfChapters": 10,
        "order": 14,
    },
    {
        "code": "NEH",
        "name": "Nehemiah",
        "numberOfChapters": 13,
        "order": 15,
    },
    {
        "code": "EST",
        "name": "Esther",
        "numberOfChapters": 10,
        "order": 16,
    },
    {
        "code": "JOB",
        "name": "Job",
        "numberOfChapters": 42,
        "order": 17,
    },
    {
        "code": "PSA",
        "name": "Psalms",
        "numberOfChapters": 150,
        "order": 18,
    },
    {
        "code": "PRO",
        "name": "Proverbs",
        "numberOfChapters": 31,
        "order": 19,
    },
    {
        "code": "ECC",
        "name": "Ecclesiastes",
        "numberOfChapters": 12,
        "order": 20,
    },
    {
        "code": "SNG",
        "name": "Song of Songs",
        "numberOfChapters": 8,
        "order": 21,
    },
    {
        "code": "ISA",
        "name": "Isaiah",
        "numberOfChapters": 66,
        "order": 22,
    },
    {
        "code": "JER",
        "name": "Jeremiah",
        "numberOfChapters": 52,
        "order": 23,
    },
    {
        "code": "LAM",
        "name": "Lamentations",
        "numberOfChapters": 5,
        "order": 24,
    },
    {
        "code": "EZK",
        "name": "Ezekiel",
        "numberOfChapters": 48,
        "order": 25,
    },
    {
        "code": "DAN",
        "name": "Daniel",
        "numberOfChapters": 12,
        "order": 26,
    },
    {
        "code": "HOS",
        "name": "Hosea",
        "numberOfChapters": 14,
        "order": 27,
    },
    {
        "code": "JOL",
        "name": "Joel",
        "numberOfChapters": 3,
        "order": 28,
    },
    {
        "code": "AMO",
        "name": "Amos",
        "numberOfChapters": 9,
        "order": 29,
    },
    {
        "code": "OBA",
        "name": "Obadiah",
        "numberOfChapters": 1,
        "order": 30,
    },
    {
        "code": "JON",
        "name": "Jonah",
        "numberOfChapters": 4,
        "order": 31,
    },
    {
        "code": "MIC",
        "name": "Micah",
        "numberOfChapters": 7,
        "order": 32,
    },
    {
        "code": "NAM",
        "name": "Nahum",
        "numberOfChapters": 3,
        "order": 33,
    },
    {
        "code": "HAB",
        "name": "Habakkuk",
        "numberOfChapters": 3,
        "order": 34,
    },
    {
        "code": "ZEP",
        "name": "Zephaniah",
        "numberOfChapters": 3,
        "order": 35,
    },
    {
        "code": "HAG",
        "name": "Haggai",
        "numberOfChapters": 2,
        "order": 36,
    },
    {
        "code": "ZEC",
        "name": "Zechariah",
        "numberOfChapters": 14,
        "order": 37,
    },
    {
        "code": "MAL",
        "name": "Malachi",
        "numberOfChapters": 4,
        "order": 38,
    },
    {
        "code": "MAT",
        "name": "Matthew",
        "numberOfChapters": 28,
        "order": 39,
    },
    {
        "code": "MRK",
        "name": "Mark",
        "numberOfChapters": 16,
        "order": 40,
    },
    {
        "code": "LUK",
        "name": "Luke",
        "numberOfChapters": 24,
        "order": 41,
    },
    {
        "code": "JHN",
        "name": "John",
        "numberOfChapters": 21,
        "order": 42,
    },
    {
        "code": "ACT",
        "name": "Acts",
        "numberOfChapters": 28,
        "order": 43,
    },
    {
        "code": "ROM",
        "name": "Romans",
        "numberOfChapters": 16,
        "order": 44,
    },
    {
        "code": "1CO",
        "name": "1 Corinthians",
        "numberOfChapters": 16,
        "order": 45,
    },
    {
        "code": "2CO",
        "name": "2 Corinthians",
        "numberOfChapters": 13,
        "order": 46,
    },
    {
        "code": "GAL",
        "name": "Galatians",
        "numberOfChapters": 6,
        "order": 47,
    },
    {
        "code": "EPH",
        "name": "Ephesians",
        "numberOfChapters": 6,
        "order": 48,
    },
    {
        "code": "PHP",
        "name": "Philippians",
        "numberOfChapters": 4,
        "order": 49,
    },
    {
        "code": "COL",
        "name": "Colossians",
        "numberOfChapters": 4,
        "order": 50,
    },
    {
        "code": "1TH",
        "name": "1 Thessalonians",
        "numberOfChapters": 5,
        "order": 51,
    },
    {
        "code": "2TH",
        "name": "2 Thessalonians",
        "numberOfChapters": 3,
        "order": 52,
    },
    {
        "code": "1TI",
        "name": "1 Timothy",
        "numberOfChapters": 6,
        "order": 53,
    },
    {
        "code": "2TI",
        "name": "2 Timothy",
        "numberOfChapters": 4,
        "order": 54,
    },
    {
        "code": "TIT",
        "name": "Titus",
        "numberOfChapters": 3,
        "order": 55,
    },
    {
        "code": "PHM",
        "name": "Philemon",
        "numberOfChapters": 1,
        "order": 56,
    },
    {
        "code": "HEB",
        "name": "Hebrews",
        "numberOfChapters": 13,
        "order": 57,
    },
    {
        "code": "JAS",
        "name": "James",
        "numberOfChapters": 5,
        "order": 58,
    },
    {
        "code": "1PE",
        "name": "1 Peter",
        "numberOfChapters": 5,
        "order": 59,
    },
    {
        "code": "2PE",
        "name": "2 Peter",
        "numberOfChapters": 3,
        "order": 60,
    },
    {
        "code": "1JN",
        "name": "1 John",
        "numberOfChapters": 5,
        "order": 61,
    },
    {
        "code": "2JN",
        "name": "2 John",
        "numberOfChapters": 1,
        "order": 62,
    },
    {
        "code": "3JN",
        "name": "3 John",
        "numberOfChapters": 1,
        "order": 63,
    },
    {
        "code": "JUD",
        "name": "Jude",
        "numberOfChapters": 1,
        "order": 64,
    },
    {
        "code": "REV",
        "name": "Revelation",
        "numberOfChapters": 22,
        "order": 65,
    },
];